default_mute_time: "1h"
badwords:
  - word1
  - word2
messages:
  player_muted: "&cYou are muted!"
  bad_word_alert: "&c%player% used inappropriate language: %message%"
  mute_message: "&cClick here to mute %player% for bad language!"
  mute_notification: "&c%player% has been muted for %time% for %motivation%"
  mute_menu_header: "&eMuted Players:"
  mute_menu_entry: "&e%player% - %time% remaining"
